### ISSUE TITLE
Some weird situation on mouse

### ISSUE THREAD

**Issue by afaye0211** [fifafu/BetterTouchTool#1705]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
1. Sometimes I needed to clicked twice for a single click.
2. Sometimes the mouse perform clicked & drag action when I clicked only once.

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Early 2015)
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Please update to 2.313, at least your second problem should be solved.

There is currently a bug in various Chrome based apps that can cause your first issue. Which app have you experienced this with?

**Comment by afaye0211** [comment]
hi fifafu, 

Thanks for answering. 
I did updated to latest version few days ago and indeed the second problem does not happens again. Previously it happened in Parellel Desktop with Windows 10 inside, and also on Microsoft remote desktop.

And for the first problem seems still exists. But I see there is a function that can restart BetterTouch tool. Anyway, that might be an okay walkaround for me. Look forward for your update to fix this. Thanks.
