### ISSUE TITLE
Hide BTT Touchbar until toggled by keypress

### ISSUE THREAD

**Issue by darvelo** [fifafu/BetterTouchTool#189]
#### Description of your feature request:

I would like to allow all vanilla app touchbar controls to be displayed by default, with the BTT touchbar hidden until I toggle it with a keyboard shortcut or BTT touchbar button. Right now it seems that the BTT global touchbar is displayed by default and I have to press the `x` in the corner to hide it and show the app's (for example, iBooks) touchbar controls. If I close and open my MacBook lid and return to iBooks, the BTT touchbar shows itself again, hiding the vanilla iBooks controls and requiring me to close the BTT touchbar again.

**What kind of Mac are you using?**

MBP 2016 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**

OSX 10.12.2
BTT 1.978 (569)

**Comment by fitzage** [comment]
This seems to be happening for me with the latest build. It wasn't happening before.

However, I'd like to add a little modification to this: I'd like the behavior described above to be the default globally (Show the vanilla Touch Bar by default) with the option to set certain apps to show the BTT Touch Bar by default instead.

The reason for this is that some apps don't have Touch Bar support, and some may never have it. And some may just have crappy Touch Bar options, so I want to be able to set those apps to just use the BTT bar by default, while leaving the vanilla as the primary for most apps.

**Comment by fitzage** [comment]
Additional note I discovered today: if I click into an app to switch to it, it shows the standard system touchbar. If I command-tab to it (which is what I do 99.99999999% of the time), this is when it shows the BTT bar instead. @darvelo Can your verify this is what happens for you?

**Comment by fitzage** [comment]
Additional testing: While the above still seems to be true…
1. If I command-tab between two apps that have custom BTT Touch Bar buttons, it shows the BTT bar instead of the default.
2. If I command-tab from an app where I don't have custom BTT buttons to one where I do have custom BTT buttons:
    1. Usually, if the app I'm switching too isn't the first option (like I have to hit command-tab-tab), it will show the BTT bar instead of the system bar.
    2. If the app I'm switching to is the first option (just have to hit command-tab), it will show the system bar instead of the BTT bar.

Weird, huh?

**Comment by fifafu** [comment]
I have identified one issue that caused the "Show Default Touch Bar" setting to not work, maybe that was causing your issues? (fixed in 1.981)

In general make sure the "hide BTT Touch Bar if nothing to show" option is activated
![image](https://cloud.githubusercontent.com/assets/8820811/21778201/b8206eac-d6a2-11e6-9a8a-181dd147410e.png)

**Comment by fitzage** [comment]
I've always had that activated.

**Comment by fifafu** [comment]
If you press the BTT icon in the control strip to hide the BTT Touch Bar, it should remember that decision and stay hidden unless you either press that icon again or have specifically set an app to show the Touch Bar.

**Comment by fitzage** [comment]
That doesn't work, but this is interesting:

I went in and made sure Global and all individual apps were set to "Show App Default Touch Bar," and they still show the BTT bar according to the behavior listed above.

But…now that I set that, it appears that BTT is not expecting them to be showing, because it now takes two taps on the BTT icon to close them. But something is still making them activate when I switch to those apps with command-tab.

So apparently I had the configuration wrong before, and I've fixed it, but something is still making it do the wrong thing.

**Comment by fifafu** [comment]
Ah that's interesting! Have you already updated to 1.981?

**Comment by fitzage** [comment]
Haha, just updated this morning. Didn't realize there was yet another update. I was still on 1.980.

Same behavior on 1.981.

**Comment by fifafu** [comment]
Could you attach an export of your setup or send it to me via mail (boastr.net@gmail.com)? (via the export preset button)

**Comment by fitzage** [comment]
Here it is, zipped since github doesn't like the file otherwise.
[BTT-settings.zip](https://github.com/fifafu/BetterTouchTool/files/694422/BTT-settings.zip)

**Comment by fifafu** [comment]
Very weird, on my machine it seems to work as intended - the BTT Touch Bar only shows after explicitly pressing the button in the Control Strip.

On your machine the BTT Touch Bar still shows more or less randomly?

**Comment by fitzage** [comment]
Well, as seen above, I wouldn't call it random per se, but yeah.

If I set the System Preferences to just show the app shortcuts and not the control strip, it does not show the BTT bar when it's not supposed, but not when it's supposed to, either. :-) I assume BTT has to piggy back on the control strip.

After playing with the system prefs for Touch Bar a bit, and setting them back to what they were, BTT was behaving as expected except it required tapping the BTT button twice to display the BTT bar, meaning it was expecting the bar to already be showing, apparently.

I changed the Touch Bar Behavior settings in BTT back to Default, and it went back to having the problem again. Then I changed them back to "Show App Default Touch Bar," and couldn't get the problem to go away anymore, even after fiddling with the system prefs again.

So I don't know what's going on.

**Comment by fifafu** [comment]
You are right about BTT needing the System Preferences to be set to "App Controls with Control Strip".

Unfortunately I'm still unable to reproduce the issue on my machine, but I'll try it on another machine tomorrow!

**Comment by fitzage** [comment]
I was about to say it was working as expected now, and then it stopped. GRRR

**Comment by fitzage** [comment]
And then it started working again. It seems like there might be some specific sequence of events that ends up switching it between behaviors, and I can't figure out what.

**Comment by fifafu** [comment]
maybe it's related to the presses of the modifier keys during cmd+ tab, I'll look into this further!

**Comment by fitzage** [comment]
I thought it might be related to the fact that I have some Touch Bar buttons set for when Command is pressed, so I removed the modifier for all of them, to no avail.

**Comment by fifafu** [comment]
I think I may have found something - I'll try to fix it in about an hour!

**Comment by fitzage** [comment]
Looking in console, I can't help but wonder if it's related to any of this stuff, but it's probably just standard:

```
default	14:21:12.175013 -0700	NowPlayingTouchUI	[NowPlayingTouchUI] Reloading available apps due to workspace activating an application: NSConcreteNotification 0x608000240450 {name = NSWorkspaceDidActivateApplicationNotification; object = <NSWorkspace: 0x608000001d60>; userInfo = {
    NSWorkspaceApplicationKey = "<NSRunningApplication: 0x608000107a10 (com.apple.Terminal - 894)>";
}}
default	14:21:12.278797 -0700	NowPlayingTouchUI	[NowPlayingTouchUI] Updating now playing apps with 0 added and 0 removed.
default	14:21:12.278834 -0700	NowPlayingTouchUI	[NowPlayingTouchUI] Reloading control strip presence because of now playing apps reload.
```

**Comment by fifafu** [comment]
I just tried a quick fix: http://boastr.net/releases/btt1.983b.zip
If you have time it'd be great if you'd check whether that changes the behavior - I'm not entirely sure yet!

**Comment by fitzage** [comment]
So far, it's working as expected. I'll let you know if that changes.

The one problem still is that if you don't manually close the BTT bar before switching apps, it closes automatically (which I actually like) but then when you switch back to the app, BTT expects it to still be open, requiring the double tap for activation. Any way you can fix this, like maybe automatically expecting the bar to be hidden when switching to an app (based on the settings in BTT, presumably)?

**Comment by fitzage** [comment]
Seems to be working great now, and looks like you fixed that other bit where it was expecting the BTT bar to be visible when switching, because I only need to tap once in those situations.

**Comment by fifafu** [comment]
Awesome thanks a lot for all the testing!

**Comment by snickers2k** [comment]
Hey. I have the same Problem here. Send a Logfile via Email.
